export enum Actions {
    FEACH_ALL_ROOMS = 'FEACH_ALL_ROOMS',
    CREATE_ROOM = 'CREATE_ROOM',
    DELETE_ROOM = 'DELETE_ROOM',
    REGISTER_STUDENT = 'REGISTER_STUDENT',
    REMOVE_STUDENT = 'REMOVE_STUDENT'
}
