export enum Actions {
  REGISTER_STUDENT = 'REGISTER_STUDENT',
  REMOVE_STUDENT = 'REMOVE_STUDENT',
  RESERVE_ROOM = 'RESERVE_ROOM',
  ADMIN_STUDENT_ADD = 'ADMIN_STUDENT_ADD',
  ADMIN_STUDENT_EDIT = 'ADMIN_STUDENT_EDIT',
  ADMIN_STUDENT_REMOVE = 'ADMIN_STUDENT_REMOVE'
}

export enum SingleActions {
  FETCH_ALL_ROOMS = 'FETCH_ALL_ROOMS',
  FETCH_ALL_ADMINS = 'FETCH_ALL_ADMINS'
}
